# cleanup store files
alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete"

# spotlight: Search for a file using MacOS Spotlight's metadata
spotlight () { mdfind "kMDItemDisplayName == '$@'wc"; }